/* eslint-disable */
// Fill Word.freqPct / Word.freqSource from the frequency lists in data/raw/.
//
// Why this exists separately from packs:import — the importer only knows the
// `rank` carried inside a pack file, which covers the words that ended up in a
// pack. This script works straight off the source lists, so it also reaches
// words that live in the DB from data/vocabulary.json (the 3.6k core A1–B2
// set) or from an unranked pack, and it can be re-run after any import.
//
// IDEMPOTENT: only writes rows where freqPct IS NULL. Re-running changes
// nothing. Pass --force to recompute every row (use after changing the source
// priority below), and --dry-run to see the counts without writing.
//
// Percentile, never raw rank: rank is per-source and not comparable across
// lists (`mister` is rank 1 in both BSL and TSL), so each list is normalized
// against its own size — freqPct = 1 − rank / listSize, 1 = most frequent.
//
// Usage: tsx prisma/backfill-freq.ts [--dry-run] [--force]
import "./load-env";
import { PrismaClient } from "@prisma/client";
import { existsSync, readFileSync } from "fs";
import { resolve } from "path";
import { RAW_DIR, normalizeWord } from "../scripts/packs/lib/formats";
import { FreqSource, freqPctFromRank, freqPctFromZipf } from "../src/lib/freq";

const prisma = new PrismaClient();
const DRY_RUN = process.argv.includes("--dry-run");
const FORCE = process.argv.includes("--force");

// Source priority, best general-frequency scale first. A word found in an
// earlier list is never looked up in a later one, so a general percentile is
// preferred over a domain-list percentile for the same word.
//
// NOTE: the top tier is a *general* NGSL list, which `packs:fetch` does not
// currently download — the pipeline only fetches NGSL-Spoken, BSL and TSL.
// Drop an NGSL 1.2 stats CSV in as data/raw/NGSL_12_stats.csv and it will be
// picked up automatically; until then, words that appear only in the general
// list keep freqPct = null and the selection engine scores them neutrally.
const SOURCES: Array<{ file: string; source: FreqSource; note: string }> = [
  { file: "NGSL_12_stats.csv", source: "ngsl", note: "NGSL 1.2 — general high-frequency English" },
  { file: "NGSL_Spoken_12_stats.csv", source: "ngsl-spoken", note: "NGSL-Spoken 1.2" },
  { file: "BSL_120_stats.csv", source: "bsl", note: "Business Service List 1.2" },
  { file: "TSL_12_stats.csv", source: "tsl", note: "TOEIC Service List 1.2" },
];

// The last-resort tier, and the only one that is not a ranked list. It is applied
// AFTER every SOURCES entry, so a word that appears on a real frequency list keeps
// that list's percentile — Zipf only reaches words no list covers.
//
// Generated by `npm run packs:fetch-wordfreq` (needs python3 + wordfreq). Absent
// file = tier skipped, exactly like a missing CSV above.
const ZIPF_FILE = "wordfreq_zipf.csv";

type Ranked = { rank: number; source: FreqSource; listSize: number };

// word → best (highest-priority) rank entry found for it.
function loadRanks(): { ranks: Map<string, Ranked>; loaded: string[]; missing: string[] } {
  const ranks = new Map<string, Ranked>();
  const loaded: string[] = [];
  const missing: string[] = [];

  for (const s of SOURCES) {
    const path = resolve(RAW_DIR, s.file);
    if (!existsSync(path)) {
      missing.push(`${s.file} (${s.note})`);
      continue;
    }
    // Same shape as build-wordlists.ts csvRows: header row dropped, word in
    // column 0, rank in column 1.
    const rows = readFileSync(path, "utf-8")
      .split(/\r?\n/)
      .slice(1)
      .map((l) => l.split(",").map((c) => c.trim()))
      .filter((r) => r[0] && Number.isFinite(Number(r[1])));

    for (const r of rows) {
      const word = normalizeWord(r[0]);
      // First list to claim a word wins — SOURCES is in priority order.
      if (ranks.has(word)) continue;
      ranks.set(word, { rank: Number(r[1]), source: s.source, listSize: rows.length });
    }
    loaded.push(`${s.file}: ${rows.length} rows → ${s.source}`);
  }
  return { ranks, loaded, missing };
}

// Same normalization as the importer — shared so the two paths can never drift
// into writing percentiles on two different scales.
function pctFor(r: Ranked): number | null {
  return freqPctFromRank(r.rank, r.listSize);
}

// word → Zipf, from the generated CSV. Empty map when the file is absent.
function loadZipf(): Map<string, number> {
  const zipf = new Map<string, number>();
  const path = resolve(RAW_DIR, ZIPF_FILE);
  if (!existsSync(path)) return zipf;
  for (const line of readFileSync(path, "utf-8").split(/\r?\n/).slice(1)) {
    if (!line) continue;
    // Split on the LAST comma: a few entries are multi-word ("have to"), and one
    // day one of them will contain a comma.
    const cut = line.lastIndexOf(",");
    if (cut === -1) continue;
    const word = normalizeWord(line.slice(0, cut));
    const value = Number(line.slice(cut + 1));
    if (word && Number.isFinite(value)) zipf.set(word, value);
  }
  return zipf;
}

async function main() {
  const { ranks, loaded, missing } = loadRanks();
  const zipf = loadZipf();

  console.log(`${DRY_RUN ? "🔍 DRY RUN — " : ""}Backfilling Word.freqPct${FORCE ? " (--force: recomputing every row)" : ""}\n`);
  for (const l of loaded) console.log(`  ✓ ${l}`);
  for (const m of missing) console.log(`  ⚠ absent: ${m}`);
  if (zipf.size) console.log(`  ✓ ${ZIPF_FILE}: ${zipf.size} rows → wordfreq (fallback tier)`);
  else console.log(`  ⚠ absent: ${ZIPF_FILE} (run \`npm run packs:fetch-wordfreq\`)`);

  if (!ranks.size && !zipf.size) {
    console.log("\nNo frequency data in data/raw/ — run `npm run packs:fetch` first.");
    return;
  }
  console.log(`\n  ${ranks.size} distinct ranked words available\n`);

  const words = await prisma.word.findMany({
    where: FORCE ? {} : { freqPct: null },
    select: { id: true, word: true, cefr: true, freqSource: true },
  });
  console.log(`Candidate rows: ${words.length}${FORCE ? "" : " (freqPct IS NULL)"}`);

  const updates: Array<{ id: string; freqPct: number; freqSource: string }> = [];
  const perSource: Record<string, number> = {};
  let keptRanked = 0;
  for (const w of words) {
    const key = normalizeWord(w.word);
    const hit = ranks.get(key);
    if (hit) {
      const freqPct = pctFor(hit);
      if (freqPct === null) continue; // unusable rank — leave null rather than guess
      updates.push({ id: w.id, freqPct, freqSource: hit.source });
      perSource[hit.source] = (perSource[hit.source] ?? 0) + 1;
      continue;
    }
    // The fallback tier must never DISPLACE a real list percentile. Without this
    // guard, a --force run while one of the SOURCES files happens to be absent
    // (data/raw is gitignored, so this is the normal state of a fresh checkout)
    // would quietly rewrite those rows onto the compressed Zipf band — turning a
    // missing download into a silent, column-wide rescale.
    if (w.freqSource && w.freqSource !== "wordfreq") {
      keptRanked++;
      continue;
    }

    // No ranked list covers this word — fall back to Zipf. Returns null when
    // wordfreq has never seen it, and null stays null: scored neutrally, not
    // scored "rarest".
    const freqPct = freqPctFromZipf(zipf.get(key));
    if (freqPct === null) continue;
    updates.push({ id: w.id, freqPct, freqSource: "wordfreq" });
    perSource.wordfreq = (perSource.wordfreq ?? 0) + 1;
  }

  console.log(`Matched: ${updates.length} — ${Object.entries(perSource).map(([s, n]) => `${s} ${n}`).join(", ") || "none"}`);
  if (keptRanked) {
    console.log(`Kept their existing list percentile (fallback tier not allowed to displace it): ${keptRanked}`);
  }
  console.log(`Unmatched (stay null, scored neutrally): ${words.length - updates.length - keptRanked}`);

  if (!DRY_RUN) {
    const TX = 100;
    for (let i = 0; i < updates.length; i += TX) {
      await prisma.$transaction(
        updates.slice(i, i + TX).map((u) =>
          prisma.word.update({ where: { id: u.id }, data: { freqPct: u.freqPct, freqSource: u.freqSource } })
        )
      );
      process.stdout.write(`\r  written ${Math.min(i + TX, updates.length)}/${updates.length}   `);
    }
    if (updates.length) console.log();
  }

  const total = await prisma.word.count();
  const withFreq = await prisma.word.count({ where: { freqPct: { not: null } } });
  console.log(
    `\n✅ Done. freqPct coverage: ${withFreq}/${total} (${((withFreq / total) * 100).toFixed(1)}%)` +
      (DRY_RUN ? " — unchanged, dry run" : "")
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
